services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./evolution_instances:/evolution/instances
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:CafePreto!2025@10.101.1.111:5432/evolution_db?schema=public"