services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: typebot
      POSTGRES_DB: evolution_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"